apiVersion: apps/v1
kind: Deployment
metadata:
  name: rock-paper-science-ui-app
  namespace: rock-paper-science
  labels:
    app: rock-paper-science-ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rock-paper-science-ui-app
  template:
    metadata:
      labels:
        app: rock-paper-science-ui-app
    spec:
      containers:
      - name: rock-paper-science-ui-app
        image: ghcr.io/caproni/rockpaperscienceui:${{ github.sha }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
